# Usa la imagen base de OpenJDK
FROM openjdk:22-jdk

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo JAR al contenedor
COPY target/msvc-propietarios-0.0.1-SNAPSHOT.jar app.jar

# Expone el puerto en el que la aplicación se ejecutará
EXPOSE 8001

# Ejecuta el archivo JAR
ENTRYPOINT ["java", "-jar", "app.jar"]
